### ISSUE TITLE
Storage in settings restarts app

### ISSUE THREAD

**Issue by xXShiina** [FengMoeTeam/NHentai-android#35]
I'm not sure if this is only me but, When I go to settings in the app and select storage, the app will say that it has stopped responding, then it will restart.

**Comment by NotCR** [comment]
What version are you using? The latest apk in releases or did you compile the source?

**Comment by NotCR** [comment]
Also. check if you are giving storage permissions to the app in Settings->app->NHBooks->Permissions

**Comment by xXShiina** [comment]
I'm using version 1.4.0(21). I just cloned the repository from the front page. I assumed that was the latest version.

Granted I really don't know how to use github.

**Comment by xXShiina** [comment]
I've also granted permissions to the app. But I recently found out that my SD card for my phone is in write protection, but I'm not sure if that affects anything.

**Comment by NotCR** [comment]
we dont actually use the sd card, we use the internal storage. I cannot replicate the problem. if you could use Android Studio to get the exact error, it would be really helpful

**Comment by NotCR** [comment]
Apart from that really strange problem, is everything working okay or as expected?

**Comment by xXShiina** [comment]
Just a question, How would I simulate the error in Android Studio? It was really a miracle that I actually figured out how to get the app to my phone at all lol.

I really don't understand Android Studio, So I'm not sure if I could simulate the error. Unless its just connecting my phone to the computer and then running the app with Android Studio enabled then try to open the storage in the app.

**Comment by NotCR** [comment]
Yeah, connect your phone, press play in android studio, select your phone  and try to open the storage in settings. If an error occurs you can see it on the Android Monitor TAB. Example Below (Im using a simulator) 

![image](https://cloud.githubusercontent.com/assets/16932169/17090192/f8ce58bc-51f3-11e6-8573-e5528ba2754f.png)

**Comment by xXShiina** [comment]
Alrigjt, Sorry for the delay in my response. 

I think this is the file that you need.



[idea.zip](https://github.com/FengMoeTeam/NHentai-android/files/383055/idea.zip)

**Comment by NotCR** [comment]
okay boy, should be fixed in https://github.com/FengMoeTeam/NHentai-android/commit/ebf64a0f54211213323e98ab94bebf763741c22c that is now live. Update the project and u should be good to go

Just confirm that the change fixes the problem (It was fixed on 2 emulators with android 4.2 and 4.4 in my side)

**Comment by NotCR** [comment]
@xXShiina can you confirm the fix so i can close this issue please
