### ISSUE TITLE
Is this app support Android 4.2?

### ISSUE THREAD

**Issue by talatuanpro** [FengMoeTeam/NHentai-android#49]
I always get this error:

`There is a Problem Parsing the Package.`

I'm using LG-LU6200.

**Comment by NotCR** [comment]
Yes It does API 17 onward (4.2)

1 of 2 - Bad download of the apk or u have installed an older apk signed by someone else (Not Us).

Do you have an older version of the app? is it the first time you install it?

**Comment by talatuanpro** [comment]
This is my first time download this.
And i don't have any older version of this app.

**Comment by talatuanpro** [comment]
I tried app-release, it worked.
Sometimes app crash when i finish reading and press <-- on screen. But that's okay. I guess when i upgrade Android to 4.2, i forgot something...
Anyways, thanks!

**Comment by NotCR** [comment]
can you do me a favor in  internalstorage/NHBooks/Logs there should be all of your crashlogs, if you can post them here in zip i might be able to see whats causing the crash.
