### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by panslothda** [FengMoeTeam/NHentai-android#58]
Im using a oneplusone with cyanogenmod android 6.0.1 appversion NHBooks-1.6.3-beta30.apk

The app keeps on crashing every few minutes. sometime it takes 5 seconds after opening the app sometimes it works for 5 minute without problem. its completely random and no pattern is emerging.

I tried starting only app after restarting phone to verify it isn't a ram issue. Keeps on crashing. There is over 30 GB free space on the sd card.

Any kind of logs i can pull to help with the debugging?

**Comment by NotCR** [comment]
Can you please check in internal storage/NHBooks/logs and attach them in a zip so i can debug them, thanks

**Comment by panslothda** [comment]
Sure :) Heres the folder.
[Logs.zip](https://github.com/FengMoeTeam/NHentai-android/files/518250/Logs.zip)

**Comment by panslothda** [comment]
Btw i just realised that. A nice feature to have would be a function that would look through the downloaded folders and see if any of them are near finished but not really and would automatically resume the downloads. because i have quite some Downloaded but alot of them are half finished because the app crashed and sometimes its hard to see which ones are fully downloaded or not by only looking into folder since only the fully downloaded once appear in the saved books place.

**Comment by NotCR** [comment]
Hello there, i checked the logs but unfortunetly whatever its crashing the app is from one plus, its crashing in one of the android core libraries (nothing i can actually debug). im going to release a update (soon TM) with a few library updates hoping it fixes the issue

**Comment by panslothda** [comment]
ok nice :) i was able to reproduce and isolate the issue int he meantime. it happens when i open a doujhin page and then before it finishes loading and is just a white screen when i press back either on top of the screen or with android back it crashes by me. maybe that helps but its still ok tough since i know now what not todo

**Comment by NotCR** [comment]
hey there, i just released an update upgrading all of the android core libraries and fixing other things. Can you check if the problem exists, and if it does can u send me the new logs to check them

**Comment by panslothda** [comment]
So i updated and well now it doesn't crash anymore while going back.. but everytime i open the saved books page and scroll down further then the 4 first doujins it crashes. 100 % reproducible.
[Logs.tar.gz](https://github.com/FengMoeTeam/NHentai-android/files/597202/Logs.tar.gz)

i uploaded the logs folder but i don't think it generates as the last logs where made a week ago and i crashed the application around 10 to 20 times in last 2 days...

**Comment by NotCR** [comment]
@panslothda the zip folder is empty, but my guess its that in /internal storage/nhentai/books theres a folder named "null", erasing it should fix the problem.

**Comment by panslothda** [comment]
yep that fixed it :)

And how the heck did i manage to upload a empty folder XD

Anyhow seems like its all working now .


Thank you so much for all of your work :T

**Comment by NotCR** [comment]
im pretty sure it has to do with this in my release disclaimer.

1 When upgrading don't use the app for 30 seconds so it can update the data of the old saved books and old favorite books. (If you have many saved books or favorite books consider leaving it a little longer 1-2 minutes)

i dont know where exactly is creating the null folder, but im going to refine the algorithm to check for nulls and things like that, so it doesnt crash.

PS. Glad you are enjoying the app

**Comment by panslothda** [comment]
Hmm that would surprise me because i opened the app and left the phone just do its magic after opening the app for aroubd 20 minutes...

But i had a null folder beforehand. Like in the saved books tab i had a doujhin with the name null und no pictures and it was empty.

Had that since a few weeks inside the app.

**Comment by NotCR** [comment]
@panslothda new version up should fix the null directory being scanned + Auto Update feature (Beta)(It Works)

**Comment by panslothda** [comment]
Using 1.7.2 i keep on getting crashes but now they arent in a pattern. Completly random sometines in search function sometimes i. Reading something

**Comment by NotCR** [comment]
@panslothda this is a one plus specific problem with their android libraries implementation or at least that's where the problem is pointing (Android Motion Event).

**Comment by panslothda** [comment]
Hmm ok so i guess then cant change it. Oh well gotta live with random crashes then^^ should i close ticket?

**Comment by maximum800** [comment]
I have the same problem, plus I can not save or download anything (a sort of permission error  occurs on android 6.)
