### ISSUE TITLE
use gallery id instead of gallery name for folder name (and cache?) or let me rename it

### ISSUE THREAD

**Issue by crankshaftman** [FengMoeTeam/NHentai-android#70]
my android doesn't support　|\<>/"?*:　for files and folders name

many galleries name contains one or more characters I mentioned above

so I can't save any galleries, and images doesn't show up

galleries without those characters above works perfectly fine though

sorry for my bad english, thank you

**Comment by NotCR** [comment]
i had this in mind since a while a go, going to try to implement it for next update. Thanks for your feedback.

**Comment by NotCR** [comment]
should be fixed in latest release.
