### ISSUE TITLE
[API] Official RESTful API response error

### ISSUE THREAD

**Issue by Beckylemmesmash** [FengMoeTeam/NHentai-android#81]
Basically, I opened NHBooks and it told me there was an update, I tried to download and it failed. So what I did was, I uninstalled the 1.8.3 version of NHBooks to install the 1.8.4 version, and after all that's done - after everything was looking good - "Can't connect to NHentai" I tried everything on my phone, use vpn and connect, uninstall NHBooks and install it again, restart my phone.. everything and I still can't connect to NHentai from the 1.8.4 version of NHBooks.

**Comment by Beckylemmesmash** [comment]
@NotCR

**Comment by advrieldra** [comment]
yeah i have same problem,

**Comment by kenziefc** [comment]
Pretty sure this is from nhentai's backend, their API request returns error.

**Comment by NotCR** [comment]
Nhentai backend Is returning {"error": true}. maybe @nhentai Is doing upgrades

**Comment by ianeva** [comment]
Me 2,
when I update, there's suck. then I had to Downgrade to 1.8.3(Beta 35) but also can't connect to them.
there's 2 condition I can use it : searching with tittle(not works any title of book) and random search

**Comment by ianeva** [comment]
help us.

**Comment by ianeva** [comment]
@nhentai
@NotCR 
@Beckylemmesmash

**Comment by Beckylemmesmash** [comment]
I can't do anything so I'm in the same position you're in, @ianeva. So, let's leave it to the devs and hopefully, they fix it.

**Comment by NotCR** [comment]
@ianeva  @Beckylemmesmash  @advrieldra Reported the problem to the site owner(@nhentai). He is going to check whats happening

**Comment by kowith337** [comment]
Same here, but I didn't upgrade to latest version due to I've installed from F-Droid repo, currently F-Droid didn't build new version yet.

I can access favourite books and saved books, but sometime can lead to app crash.

Maybe I need to wait until newer update than 1.8.4 or until NHentai fixed the API problem.

**Comment by ianeva** [comment]
Thank You, 
waiting for fix with web mode :3

**Comment by Beckylemmesmash** [comment]
Thank you so much, @NotCR!

**Comment by NotCR** [comment]
@Beckylemmesmash @ianeva @kowith337 @kenziefc  @advrieldra looks like its fixed i can normally browse again

**Comment by ianeva** [comment]
thank you, 
Works for me 
@NotCR
@nhentai

**Comment by Beckylemmesmash** [comment]
Thank you so much for fixing the issue, @nhentai @NotCr! Cheers!
